--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/android:api-28-node"
    environment: 
      JVM_OPTS: "-Xmx3200m"
    steps: 
      - checkout
      - 
        run: 
          command: |
              wget https://services.gradle.org/distributions/gradle-4.0.2-bin.zip -P /tmp
              sudo unzip -d /opt/gradle /tmp/gradle-*.zip
              echo 'export GRADLE_HOME=/opt/gradle/gradle-4.0.2' >> $BASH_ENV
              echo 'export PATH=$PATH:/opt/gradle/gradle-4.0.2/bin' >> $BASH_ENV
              source $BASH_ENV
          name: "Install gradle"
      - 
        run: 
          command: "sudo npm install -g ionic cordova yarn\n"
          name: "Install ionic and cordova"
      - 
        run: 
          command: "yarn install\n"
          name: "Install npm packages"
      - 
        run: 
          command: |
              ionic cordova platform add android --noresources
              ionic config set -g telemetry true
          name: "Install Cordova plugins and add android platform"
      - 
        run: 
          command: |
              ionic cordova build android --verbose
              mkdir -p /tmp/apk
              cp -r platforms/android/app/build/outputs/apk/debug/app-debug.apk /tmp/apk
          name: "Generate apk"
      - 
        store_artifacts: 
          destination: apks
          path: /tmp/apk
    working_directory: ~/repo
version: 2
workflows: 
  build_and_deploy: 
    jobs: ~
  version: 2
