--- 
jobs: 
  build: 
    docker: 
      - image: "retengr/opt-ionic"
    environment: 
      JVM_OPTS: "-Xmx3200m"
    steps: 
      - checkout
      - run: 
          command: |
              ionic cordova platform add android --noresources
              ionic config set -g telemetry true
          name: "Install Cordova plugins and add android platform"
      - run: 
          command: |
              ionic cordova build android --verbose
              mkdir -p /tmp/apk
              cp -r platforms/android/app/build/outputs/apk/debug/app-debug.apk /tmp/apk
          name: "Generate apk"
      - 
        store_artifacts: 
          destination: apks
          path: /tmp/apk
    working_directory: ~/repo
version: 2
workflows: 
  build_and_deploy: 
    jobs: 
  version: 2
